### ISSUE TITLE
Change Capture With Sql  EXCEPT Performance 

### ISSUE THREAD

**Issue by rongfengliang** [castledio/castled#49]
castled use EXCEPT for Change Capture, current I use one Postgres like  database as  OLAP  data warehouse. but when I do some tests with Large datasets.  that will cause timeout. 

My use case, one table first time with  200000 rows. and then we use ETL to ingest 2 million  rows ,  we found castled not working. we do some tests   found that caused by timeout 

How can  I do for this . or any plan for support data partition  for better performance

**Comment by aruntcet2010** [comment]
@rongfengliang do you have a loaded timestamp on the tables you are trying to sync?

**Comment by rongfengliang** [comment]
@aruntcet2010  Thanks.   I do some tests figure out that caused by default database query timeout conf.  timestamp  is a better choice but currently we can't use it, because we don't trust it (sometimes data had changed but timestamp does not change ).  I think support data partition maybe have better performance

**Comment by aruntcet2010** [comment]
@rongfengliang whats the database you are using?

**Comment by rongfengliang** [comment]
> @rongfengliang whats the database you are using?

Thanks,currently I do some tests with sql except for databases that support this feature . I had test yugabytedb, oceanbase, cratedb, dremio (query engine) . I want write more db poller for our business

**Comment by aruntcet2010** [comment]
@rongfengliang Are you facing timeouts with all these databases or just a few? 

We do have a plan to use timestamps to speed up the except queries. We understand that timestamps are not very reliable since transactions can be long running in data warehouses. But we intend to use that to provide a buffer for the except queries(say even 24 hours). That we believe will fasten up the except queries and will be reliable.

What exactly do you mean by data partitioning without using an updated timestamp?

**Comment by aruntcet2010** [comment]
@rongfengliang We have tried delta computation up to even 50 million records in a postgres database and upto billions of records with warehouses like Redshift, BigQuery and Snowflake, with small to medium sized clusters. We did not see any performance issues there

**Comment by rongfengliang** [comment]
@aruntcet2010  Thanks, Not all databases facing timeouts. most because default timeout conf 
We don't use BigQuery or Snowflake, cloud warehouse, all build on-premise so with large Datasets may cause Performance. castled is awesome. but currently, I want to find a better way to change  capture data  with a  good  Performance,  so we can add more database support for castled

**Comment by aruntcet2010** [comment]
@rongfengliang we are already using sort/distribution/partition keys in data pollers. Refer [RedshiftDataPoller](github.com/castledio/castled/blob/main/connectors/src/main/java/io/castled/warehouses/connectors/redshift/RedshiftDataPoller.java), where we use the primary keys selected by the user as the sort/distribution keys, which fastens up the queries a lot.

**Comment by aruntcet2010** [comment]
> @rongfengliang Are you facing timeouts with all these databases or just a few?
> 
> We are already using the primary keys as partition keys in most of our warehouses. So if the database can make use of partitioned data, the queries will be much faster. You might want to run the tests with some key as a partition key and check, if that fastens up the query.
> 
> We also have a plan to use update timestamps to speed up the except queries. We understand that timestamps are not very reliable since transactions can be long running in data warehouses. But we intend to use that to provide a buffer for the except queries(say even 24 hours). That we believe will fasten up the except queries without compromising the data reliability.

what about these strategies?

**Comment by aruntcet2010** [comment]
@rongfengliang If we have to sync an entire table and not a query, we can event read from write ahead logs. For instance in case of Postgres, We could use Postgres Logical Replication also.

**Comment by rongfengliang** [comment]
@aruntcet2010  Thank you so much, Currently, We plan to use debezium+ castled for Revert ETL, Some warehouses can use CDC, but  others can't, so  currently  we do some tests to find one  better  way  for  these can't use CDC  or except  performance too  slow

**Comment by aruntcet2010** [comment]
@rongfengliang another approach i can think of is to create a hash out of an entire record and compare just the hash instead of comparing all the rows. I think that can be pretty faster if partition the data based on the hash column.
