### ISSUE TITLE
Support authorization

### ISSUE THREAD

**Issue by rongfengliang** [castledio/castled#87]
**Is your feature request related to a problem? Please describe.**

We want to do authorization for uses who can create pipelines. and who can trigger pipelines etc

**Describe the solution you'd like**

May add  RBAC for authorization management. or provide  some  extension we can implement

**Comment by aruntcet2010** [comment]
@rongfengliang multi-user support or role based access is currently out of scope for our open source project. But you are free to create a private fork and add those features and use it for yourself.

**Comment by rongfengliang** [comment]
> @rongfengliang multi-user support or role based access is currently out of scope for our open source project. But you are free to create a private fork and add those features and use it for yourself, if its for your internal use.

Thanks
